spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CnKart
    username: root
    password: rootroot
  jpa:
    properties.hibernate-dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update