spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CNPayment?createDatabaseIfNotExists=true
    username: root
    password: 1234
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
